### ISSUE TITLE
Add option to use shortcut keys (F5, F6, F7) in place of Spotify API calls

### ISSUE THREAD

**Issue by benlmyers** [dvx/lofi#178]
I love Lofi and have been using it for a while now. One thing I've noticed is how annoying the API call overload error is. If we had an option in Settings to replace the back, skip, and playback buttons' actions to those of the F5 (rewind), F6 (toggle playback), and F7 (skip) keys (on Windows), this could solve the problem of play/pause/skip lag waiting for the API to respond as well as the API overload problem.

**Comment by stamoun** [comment]
You can setup media keys for Windows, this is not related to Lofi. I mean you could setup the same thing with only Spotify running.

The only way that Lofi can control playback is through API calls, if it's being throttled, we are dead in the water.

Also note that F5 (rewind), F6 (pause/play), etc. is connected to your hardware (keyboard/laptop), F5 could be rewind on your keyboard/laptop but it can be F10 (as is the case for mine) on others. 

One thing you may want to look at, in order to address this, is the media keys support in Chrome is through the `chrome://flags/#hardware-media-key-handlin` flag (or firefox through `about:config` and check if `media.hardwaremediakeys.enabled` is set to `true`)

**Comment by stamoun** [comment]
Closing this as I don't think this is a Lofi issue, feel free to reopen it if you disagree.
