### ISSUE TITLE
Can not click on top half of the pop-up

### ISSUE THREAD

**Issue by alphaemu** [dvx/lofi#264]
I saw some similar issues to this but there didn't seem to be a solution other than going to settings or updating, but I literally just downloaded the newest version and I can't access the settings because they're in the top left corner.

![image](https://user-images.githubusercontent.com/72756810/235167418-db35a897-d45b-415e-a9a6-0d55fa8c8e44.png)
My mouse here was at the bottom of the popup, but the moment I move it a few pixels upwards passed the change song icons, the UI all disappears and becomes non-interactable. Are there any fixes to this? Apologies if this is a duplicate of a different issue, I swear I looked through the current issues first. Any help is appreciated!

**Comment by stamoun** [comment]
What version is that (click on the `?` in the lower right or in right-click on the lofi icon in the system tray)?

I'm asking because I couldn't update the web site to point to the latest 2.0 release (available [here](https://github.com/dvx/lofi/releases/tag/v2.0.0))
If you downloaded from the main [site](https://lofi.rocks) then it's an older version that had that bug.

**Comment by alphaemu** [comment]
Ahh that would do it, apologies for the outdated bug then. I'll go grab the newest version. Thanks for the assist!

**Comment by stamoun** [comment]
No worries, I really need to fix that lofi.rocks update issue :/ (or rewrite to a simpler static page type thing)
