### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by adamnowek** [dvx/lofi#92]
When I click on the login button, it directs my browser to a page (http://auth.lofi.rocks/login) that says "Application error".

**Comment by stamoun** [comment]
I believe this is no longer the case (there was a hiccup with heroku a few days back that may have caused this), can be closed.

**Comment by pw000** [comment]
I'm having this same issue in all browsers. Full error:

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by dvx** [comment]
I just re-deployed the Heroku app. It should be fine now. But this is also happening because the server is getting clobbered with `refresh_token=null` requests, and the (free) instance I use occasionally crashes. The log is *constantly* getting spammed with:

![image](https://user-images.githubusercontent.com/954589/100799151-7c399380-33d9-11eb-936d-edf26b0357f6.png)

(IP addresses redacted)

**Comment by ddirgo** [comment]
Getting this error today.

**Comment by dvx** [comment]
Should be fixed by next release (1.6.0).
